import NavBar from './components/NavBar'
import './globals.css'
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body lang='en'>
      <main className="bg-red-200 min-h-screen  m-0 p-0">
      <main className="max-w-screen-2xl m-auto bg-white w-full">
        <NavBar />
       
        {children}
        </main>
        </main>
        </body>
    </html>
  )
}
// AFTER
{/* <main className="bg-red-200 min-h-screen  m-0 p-0">
      <main className="max-w-screen-2xl m-auto bg-white  w-full"></main> */}

// AFTER

// BEFORE
{/* <main className="bg-red-200 min-h-screen w-screen m-0 p-0">
      <main className="max-w-screen-2xl m-auto bg-white w-screen"></main> */}

      //BEFORE